name: GPGN268_MarsProject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - ipykernel
  - pip
  - scipy
  - xarray
  - pip:
    - nbformat
    - lxml
